baseurl      = "https://akhilsasidharan.in"
relativeURLs = true
title        = "Somethings"
languageCode = "en-us"
theme        = "the-roots-home"
paginate     = 10
disqusShortname = "akhilsasidharan-in"
enableInlineShortcodes = true
  
#enableGitInfo=true
enableEmoji= true
enableRobotsTXT= true

# Syntax Highlight Options
pygmentsCodeFencesGuessSyntax = true
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsStyle = "vs"

[author]
  name = "Akhil Sasidharan"

[pygmentsOptions]
  linenos= true

[markup]
  defaultMarkdownHandler= "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  # Subtitle for home

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "There's a <a target=\"_blank\" href=\"https://www.youtube.com/watch?v=Yhi6y1XWb-E\">bluebird</a> in my heart"
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"
#[permalinks]
#  posts = "/posts/:year/:month/:title/"
  footerRight = "<a target=\"_blank\" href=\"https://github.com/sasidakh\">Akhil Sasidharan</a>"
  footerLeft  = "Powered by <a target=\"_blank\" href=\"http://gohugo.io\">Hugo</a>, <a target=\"_blank\" href=\"https://orgmode.org/\">Emacs Org Mode</a> and org exporter <a href=\"https://ox-hugo.scripter.co/\">ox-hugo</a> plugin."

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/sasidakh"
    
  [[params.social]]
    name = "email"
    url  = "mailto:akhilsasidharan1991@gmail.com"
    
  [[params.social]]
    name = "github"
    url  = "https://github.com/sasidakh"
    
  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/akhil-sasidharan-848853140/"

  [[params.social]]
    name = "npm"
    url = "https://www.npmjs.com/~sasidakh"
    
  [[params.keys]]
    name = "gpg"
    url  = "sasidakh.gpg"
    target = "_self"
    handle = "C5AC 1A6F DDFB 90C8 4AE4  3265 7723 DF00 F489 850F"
    
[taxonomies]
    category = "categories"
    tag      = "tags"
#    series   = "series"

[languages]
  [languages.en]
    title = "Akhil Sasidharan"
    subtitle = "Somethings to say"
    keywords = ""
    # copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd ~"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
