baseurl      = "https://akhilsasidharan.in"
relativeURLs = true
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
disqusShortname = "akhilsasidharan-in"
[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Writes kick-ass code"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My Blog"
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"
#[permalinks]
#  posts = "/posts/:year/:month/:title/"
  footerRight = "Github: <a href=\"https://github.com/sasidakh\">Akhil Sasidharan</a>"
  footerLeft  = "Powered by <a href=\"http://gohugo.io\">Hugo</a> and <a href=\"https://orgmode.org/\">Emacs Org Mode</a>"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/sasidakh"

  [[params.social]]
    name = "email"
    url  = "mailto:akhilsasidharan1991@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/sasidakh"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/akhil-sasidharan-848853140/"
[taxonomies]
    category = "categories"
    tag      = "tags"
#    series   = "series"

[languages]
  [languages.en]
    title = "Akhil Sasidharan"
    subtitle = "Somethings to say"
    keywords = ""
    # copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd ~"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
  [[menu.main]]
    identifier = "work"
    name       = "Work"
    url        = "work/"