baseurl      = "https://akhilsasidharan.in"
relativeURLs = true
title        = "Somethings"
languageCode = "en-us"
theme        = "PaperMod"
paginate     = 10
disqusShortname = "akhilsasidharan-in"
enableInlineShortcodes = true
buildDrafts = false
buildFuture = false
buildExpired = false
# googleAnalytics = "UA-123-45"
#enableGitInfo=true
enableEmoji = true
enableRobotsTXT = true

# Syntax Highlight Options
pygmentsCodeFencesGuessSyntax = true
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsStyle = "vs"

[minify]
  disableXML = true
  minifyOutput = true

[author]
  name = "Akhil Sasidharan"

[pygmentsOptions]
  linenos= true

[markup]
  defaultMarkdownHandler= "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = [ "HTML", "RSS", "JSON" ]

[params]
  comments        = true
  env             = "production"
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  # Subtitle for home

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false
  ShowShareButtons = true
  # Enable sharing buttons, if you linke
  enableSharingButtons = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true
  ShowReadingTime = true
  ShowPostNavLinks = true
  # Metadata mostly used in document's head
  keywords = ["blog", "functional programming"]
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "auto"
#[permalinks]
#  posts = "/posts/:year/:month/:title/"
  footerRight = "<a target=\"_blank\" href=\"https://github.com/sasidakh\">Akhil Sasidharan</a>"
  footerLeft  = "Powered by <a target=\"_blank\" href=\"http://gohugo.io\">Hugo</a>, <a target=\"_blank\" href=\"https://orgmode.org/\">Emacs Org Mode</a> and org exporter <a href=\"https://ox-hugo.scripter.co/\">ox-hugo</a> plugin."

  [params.homeInfoParams]
    Title = "Hi there 👋"
    Content = "I am Akhil Sasidharan. I like to code. Thankfully I also get paid to code."
  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = [ "title", "permalink", "summary", "content" ]

  [[params.socialIcons]]
    name = "twitter"
    url  = "https://twitter.com/sasidakh"
    
  [[params.socialIcons]]
    name = "email"
    url  = "mailto:akhilsasidharan1991@gmail.com"
    
  [[params.socialIcons]]
    name = "github"
    url  = "https://github.com/sasidakh"
    
  [[params.socialIcons]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/akhil-sasidharan-he-him-848853140"

  [[params.socialIcons]]
    name = "npm"
    url = "https://www.npmjs.com/sasidakh"

  [[params.socialIcons]]
    name = "instagram"
    url = "https://www.instagram.com/sasidakh"

  [[params.socialIcons]]
    name = "gpg"
    url  = "sasidakh.gpg"
    target = "_self"
    handle = "C5AC 1A6F DDFB 90C8 4AE4  3265 7723 DF00 F489 850F"
    
[taxonomies]
    category = "categories"
    tag      = "tags"
#    series   = "series"

[languages]
  [languages.en]
    title = "Akhil Sasidharan"
    subtitle = "Somethings to say"
    keywords = ""
    # copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd ~"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

[menu]
  [[menu.main]]
    identifier = "tech"
    name       = "Tech"
    url        = "tech/"
    weight     = 10
  [[menu.main]]
    identifier = "poems"
    name       = "Poems"
    url        = "poems/"
    weight     = 20
  [[menu.main]]
    identifier = "categories"
    name       = "Categories"
    url        = "categories/"
    weight     = 30
  [[menu.main]]
    identifier = "tags"
    name       = "Tags"
    url        = "tags/"
    weight     = 40
  [[menu.main]]
    identifier = "search"
    name       = "Search"
    url        = "search/"
    weight     = 50
