---
title: "Functional Programming"
date: 2020-09-18T19:13:28+05:30
draft: false
categories: ["Programming"]
tags: ["functionalprogramming", "js", "javascript", "lambdacalculus"]
---

I’ve been going through some functional programming concepts because
I’m on a quest to write better code, and someone told me functional
programming is the way to go. I was intrigued and so, I read about it
and found out that it was based on lambda calculus and was even more
intrigued because it said “calculus”.

The mathematical definition of function is 'a relationship between two
sets of values such that every element in the first set has a unique
value in the second set'.

Examples:
- f(x) = x^2 + 1
- f(x) = cos(x)
- f(x) = mother of x
- f(x) = xx
- f(x) ={ |x| | x ∈ N }, where N is the set of natural numbers.
The values of x makes the first set and the evaluated values makes the
second set.

These functions are called *pure functions* in computer science. A
pure function is a function where the return value is determined by
only its input values without any observable *side effects*. If you
look at the second example above cos(x) will always return the same
value for a given x.
#+Name: EgPF
#+BEGIN_SRC js
  const add = (a, b) => a+b;
  add(3, 4) // = 7
#+END_SRC
Same function with a side effect.
#+Name: EgPFSideEffect
#+BEGIN_SRC js
  const add = (a, b) => {
    console.log(`adding ${a} and ${b}.`); // this is a side effect.
    return a+b;
  }
  add(3, 4) // = 7
#+END_SRC
Pure functions are very useful in a special kind of optimisation
called *memoization*. Since for a given value x the value of f(x) will
always remain the same it can be saved for future evaluations and can
speed up expensive function evaluations.

In maths a variable x once assigned a value does not change. That is
to say that when a variable x = 1 it cannot be reassigned to x = 3 or
we cannot mutate x to be ++x. Such an expression would be absurd to a
mathematician. We follow the same in functional programming and it is
called *immutability*.

#+Name: EgPFImmutable
#+BEGIN_SRC js
  const options = { param1: 100 };
  const addParam2 = opts => { 
    opts.param2 = 200; 
    return opts;
  }
  console.log(addParam2(options)) // { param1: 100, param2: 200 }
  console.log(options) // { param1: 100, param2: 200 }
#+END_SRC

In the above snippet addParam2 function changes the options variable so any
code that uses the options variable after will produce incosistent
values. Using variables this way will also force us to keep track of
all the changes to variables, which is a terrible debugging nightmare.

Instead do this:
#+Name: EgPFImmutable
#+BEGIN_SRC js
  const options = { param1: 100 };
  const addParam2 = opts => ({ param2: 200, ...opts });
  console.log(addParam2(options)) // { param1: 100, param2: 200 }
  console.log(options) // { param1: 100 }
#+END_SRC

Immutability is important because in an expression such as the following;
#+Name: EgPFImmutable2
#+BEGIN_SRC js
  const sq = x => x ** 2;
  const equation = x => 3 * sq(x) + 5 * x + 6 // ax^2 + bx + c
  equation(5); // = 106
#+END_SRC
If we replace equation(5) with its value 106 it does not change the
behaviour of the program in anyway. Such expressions are said to be
*referentially transparent*.

In functional programming paradigm functions are first-class which
means they are treated like any other variable. They can be passed to
a function or returned from a function. Such functions are called
*Higher-Order functions*.

#+Name: EgPFHigherOrder
#+BEGIN_SRC js
  const makeAdjectifier = adjective => noun => `${adjective} ${noun}`;
  const coolifier = makeAdjectifier('cool');
  console.log(coolifier('cat')); //cool cat
#+END_SRC

Consider this program to find the sum of a list of numbers.
#+Name: EgPFHigherOrder
#+BEGIN_SRC js
  const arr = [ 100, 20, 40, 60, 10, 70 ];
  var sum = 0;
  for (let i = 0; i < arr.length; i++) {
    sum += arr[i]; // we violate the immutability rule here.
  }
#+END_SRC
As you can see we are adding to the variable sum at every iteration
and mutating the value. Consider this solution using the inbuilt
reduce function.
#+Name: EgPFHigherOrder
#+BEGIN_SRC js
  const arr = [ 100, 20, 40, 60, 10, 70 ];
  const sum = arr.reduce((sum, cur) => sum + curr, 0); //higher-order
						       //reduce function
#+END_SRC
Higher-order functions are essential to writing correct functional code.
